### ISSUE TITLE
Unable to connect using RocketMod (Unturned)

### ISSUE THREAD

**Issue by encloinc** [pushrax/node-rcon#18]
Im trying to connect via the default example to an unturned rcon server, but its not authenticating properly and im not getting any responses from the server. I have disabled tcp aswell and this doesn't fix the issue. Any help?

**Comment by pushrax** [comment]
Got any server or client debug logs that might help in tracking down the issue?

**Comment by pushrax** [comment]
It's possible that 5155353f3c359af80ddf2ed55edebebb6137b0b1 fixes whatever issue you were having, feel free to reopen if this is still relevant to you.
