### ISSUE TITLE
Get console messages

### ISSUE THREAD

**Issue by ThisLightMan** [pushrax/node-rcon#19]
Is it possible to get console messages when they are sent through RCON?

**Comment by pushrax** [comment]
Anything sent by the server should show up in the [response callback](https://github.com/pushrax/node-rcon/blob/52d1088c4183eb06856c847bcfc6783ad3e793e2/examples/stdio.js#L18-L19). Are you running into a specific issue?

**Comment by Heath123** [comment]
> Anything sent by the server should show up in the [response callback](https://github.com/pushrax/node-rcon/blob/52d1088c4183eb06856c847bcfc6783ad3e793e2/examples/stdio.js#L18-L19). Are you running into a specific issue?

No, that's only when it's a response. I tried the server callback but it doesn't seem to work.

**Comment by pushrax** [comment]
There are no other documented packet types https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Requests_and_Responses.

Could you try adding a debug log to a new `else` condition in this codepath to see if you're getting back packets of an undocumented type? https://github.com/pushrax/node-rcon/blob/9c05be51b0ee48d6877cf7b52e8bd6edf0a3f555/node-rcon.js#L148-L162

**Comment by Heath123** [comment]
Never mind, I realised that the server doesn't send those over RCON
