### ISSUE TITLE
Csgo server returning "Bad Password"

### ISSUE THREAD

**Issue by JamesDolphin** [pushrax/node-rcon#21]
I am running some test code to get up and running.

I am getting an "Authed" output.

If I try to client.send('say test message');

The server console responds with "rcon from x.x.x.x:yyyy : Bad Password"

I have made sure my rcon password is correct as that is what I am using to monitor the server outputs. Any idea what the issue may be?

**Comment by Shaneajm** [comment]
Currently getting the same error. Did you ever find a fix?

**Comment by JamesDolphin** [comment]
I am not sure what I was doing wrong back then but yeah I got it working.

`const Rcon = require('rcon');

rconclient = new Rcon(ip, port, rpassword);
    rconclient.connect();

    rconclient.on('auth', async () => {
      console.log("RCON connected
    });
`

**Comment by SinaAboutalebi** [comment]
cuz u send commands after the connection & authentication , i had this issue too!
