### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by HEKOO321** [pushrax/node-rcon#23]
Hey sorry for disturbing but can you possibly tell me how do I excute commands using your rcon library, I did everything thing correctly, got "authed" message too, sorry again

**Comment by pushrax** [comment]
Once you're authed (i.e. in the `auth` callback, or somewhere else in your program after you've received the `auth` callback), call `conn.send()` with a command. For example:

```js
var Rcon = require('../node-rcon');

var conn = new Rcon('localhost', 1234, 'password');
conn.on('auth', function() {
  console.log("Authed!");
  conn.send("help");
}).on('response', function(str) {
  console.log(str);
}).on('end', function() {
  console.log("Socket closed!");
  process.exit();
});

conn.connect();
```
