### ISSUE TITLE
send() isn't work well

### ISSUE THREAD

**Issue by jonathanpecany** [pushrax/node-rcon#31]
I am trying to use the send() method from the Rcon object and sometimes it works and sometimes it doesn't. Not sure if it is suppose to sometimes not work but I am certain it is suppose to work most of the time. What is weird as well is that it is random as well. Also, when constantly running the same one, it doubles the console.log() as well every time it is sent so after about 5 calls, it would get about 25 in total console messages which is annoying.

**Comment by pushrax** [comment]
I'm not sure exactly what the problem you're encountering is, but it's possible this is improved by 5155353f3c359af80ddf2ed55edebebb6137b0b1.

I'm going to assume that fixes the issue, and if not you can reopen with more details.
