### ISSUE TITLE
Starter code not working for chivalry server

### ISSUE THREAD

**Issue by avi312singh** [pushrax/node-rcon#34]
Hi there i have this starter code for my chivalry server...
```
var conn = new Rcon('79.98.25.135', 25010, 'myPassword');
conn.on('auth', function () {
    console.log("Authed!");

}).on('response', function (str) {
    console.log("Got response: " + str);

}).on('end', function () {
    console.log("Socket closed!");
    process.exit();

});
```
However doesn't seem to do anything or print anything in console.
![image](https://user-images.githubusercontent.com/5769090/122317420-6cb50e80-cf15-11eb-9216-1e1d6e1c759e.png)

Does this documentation - https://tornbannerjira.atlassian.net/wiki/spaces/CHIVCOM/pages/9175118/RCon+Protocol not match with this RCON pacakge?

**Comment by BarryCarlyon** [comment]
Add `conn.connect();` to the end of the file

the `new Rcon` won't "auto connect" so you have to tell it to connect.
