### ISSUE TITLE
Buffer Error

### ISSUE THREAD

**Issue by ZariZaryab** [pushrax/node-rcon#36]
> (node:9308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Any fix for this error?

**Comment by pushrax** [comment]
This isn’t an error. It’s a message indicating that the generic Buffer constructor is deprecated due to being easy to use wrong, and will eventually be removed. See https://nodejs.org/api/deprecations.html#DEP0005

I’ve updated the code to use `Buffer.alloc`, which is the equivalent replacement.
