### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by ZariZaryab** [pushrax/node-rcon#37]
It sends a command to server (possibly) but, there's no response in the console. I wonder even if it sends it or not. (no error though)

**Comment by ZariZaryab** [comment]
Just figured out, it shows Authentication message but, doesn't send any commands to server

**Comment by pushrax** [comment]
Please see the example here: https://github.com/pushrax/node-rcon/blob/master/examples/basic.js

It is important to wait until the `auth` event before sending commands.

**Comment by ZariZaryab** [comment]
I'm sorry but, I used the exact same templete. Can you explain a lil bit more? 
Guess I've to send a command like /rcon status to server, how'll I do that.
Would mean much if you could help explaining

P.S. It shows Authenticated message in the console and sending help command message but, nothing else.
